---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  annotations:
    flux.weave.works/tag.helloworld: semver:*
    flux.weave.works/tag.sidecar: semver:*
spec:
  minReadySeconds: 5
  replicas: 2
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: waeller/flux-helloworld:1.0.1
        args:
        - -msg=HiWaeller
        ports:
        - containerPort: 80
      - name: sidecar
        image: waeller/flux-sidecar:1.0.0
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
